# Generated by Django 5.2.17 on 2026-09-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
