# Generated by Django 5.2.17 on 2026-09-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='code_snippet',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='category',
            new_name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='short_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
