# Generated by Django 5.2.17 on 2026-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_experience_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='code_snippet',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='short_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
